# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 21:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170209_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 8, 21, 59, 45, 516654, tzinfo=utc)),
        ),
    ]
