# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 22:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170209_0059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published_date',
            new_name='date_published',
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 8, 22, 21, 41, 651097, tzinfo=utc)),
        ),
    ]
