# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 13:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170209_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 9, 13, 15, 38, 794805, tzinfo=utc)),
        ),
    ]
